<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class QuizQuestionBankSeeder extends Seeder
{
    public function run(): void {}

    /** @return array<int, array{id: string, category: string, question: string, options: list<string>, answerIndex: int, correctAnswer: string}> */
    public static function getQuestions(): array
    {
        return [
            [
                'id' => 'pso-1',
                'category' => 'PSO',
                'question' => 'Which online platform can PSO be submitted through?',
                'options' => ['myHSSE-UAUC', 'IPSS (Integrated Process Safety Solution)', 'ePTW', 'PRIME'],
                'answerIndex' => 0,
                'correctAnswer' => 'myHSSE-UAUC',
            ],
            [
                'id' => 'pso-2',
                'category' => 'PSO',
                'question' => 'Which of the following is the best example of PSO?',
                'options' => ['Poor Condition (Corroded / Loose Piping)', 'Slippery floor', 'Non-ergonomic Equipment', 'Housekeeping'],
                'answerIndex' => 0,
                'correctAnswer' => 'Poor Condition (Corroded / Loose Piping)',
            ],
            [
                'id' => 'pso-3',
                'category' => 'PSO',
                'question' => 'Vibration of equipment does not need to be reported for PSO. Is the statement correct?',
                'options' => ['YES', 'NO'],
                'answerIndex' => 1,
                'correctAnswer' => 'NO',
            ],
            [
                'id' => 'pso-4',
                'category' => 'PSO',
                'question' => 'Complete the phrase: Report Process Safety Observations because ______.',
                'options' => ['I Care', 'It is optional', 'It saves time', 'It replaces supervision'],
                'answerIndex' => 0,
                'correctAnswer' => 'I Care',
            ],
            [
                'id' => 'pso-5',
                'category' => 'PSO',
                'question' => 'What is the correct sequence for practicing PSO (Process Safety Observation)?',
                'options' => [
                    'Report PSO via myHSSE UAUC > Mitigate to ensure safe operations > Pause and ask question when abnormality observed > Conduct frequent walkabout to identify any Process Safety hazards.',
                    'Conduct frequent walkabout to identify any Process Safety hazards > Pause and ask questions when any abnormality is observed > Intervene and mitigate to ensure continuous safe operations > Report PSO via myHSSE UAUC.',
                    'Intervene and mitigate to ensure continuous operation > Conduct frequent walkabout to identify any Process Safety hazards > Pause and ask questions when any abnormality is observed > Report PSO via myHSSE UAUC.',
                ],
                'answerIndex' => 1,
                'correctAnswer' => 'Conduct frequent walkabout to identify any Process Safety hazards > Pause and ask questions when any abnormality is observed > Intervene and mitigate to ensure continuous safe operations > Report PSO via myHSSE UAUC.',
            ],
            [
                'id' => 'competency-1',
                'category' => 'Competency',
                'question' => 'Give one example of a Competency Assessment for PETRONAS staff.',
                'options' => ['BSCPD Certification', 'PECAS/SMA', 'MyGovernance'],
                'answerIndex' => 1,
                'correctAnswer' => 'PECAS/SMA',
            ],
            [
                'id' => 'competency-2',
                'category' => 'Competency',
                'question' => 'Which action demonstrates Be Competent, Be Accountable to Do It Right?',
                'options' => [
                    'Completing a critical job without proper training because you have prior experience',
                    'Ignoring a deviation in procedure because the job seems routine',
                    'Skipping documentation for work efficiency',
                    'Reporting a hazard immediately through the UAUC system',
                ],
                'answerIndex' => 3,
                'correctAnswer' => 'Reporting a hazard immediately through the UAUC system',
            ],
            [
                'id' => 'competency-3',
                'category' => 'Competency',
                'question' => 'Arrange the following PASR steps in the correct order before starting a critical activity: 1) Verify isolation and energy control measures. 2) Review the PASR checklist required in IPSS PASR. 3) Confirm readiness of safety-critical equipment and barriers. 4) Obtain approval commencement from OIM/FM.',
                'options' => ['1 -> 2 -> 3 -> 4', '3 -> 2 -> 1 -> 4', '2 -> 1 -> 3 -> 4', '2 -> 3 -> 1 -> 4'],
                'answerIndex' => 2,
                'correctAnswer' => '2 -> 1 -> 3 -> 4',
            ],
            [
                'id' => 'competency-4',
                'category' => 'Competency',
                'question' => 'What is the definition of a Major Accident Hazard (MAH)?',
                'options' => [
                    'Any small incident that causes minor injuries',
                    'Any issue that leads only to equipment vibration',
                    'A process deviation that causes schedule delays only',
                    'Any source of danger within a process that can escalate into a major incident involving fatalities, serious injuries, environmental impact, asset loss, fires, explosions, or hazardous releases',
                ],
                'answerIndex' => 3,
                'correctAnswer' => 'Any source of danger within a process that can escalate into a major incident involving fatalities, serious injuries, environmental impact, asset loss, fires, explosions, or hazardous releases',
            ],
            [
                'id' => 'competency-5',
                'category' => 'Competency',
                'question' => 'What typically causes an MAH to escalate into a major incident?',
                'options' => ['Air-conditioning malfunction', 'Fires, explosions, or uncontrolled hazardous material releases', 'Incomplete forms', 'Website maintenance'],
                'answerIndex' => 1,
                'correctAnswer' => 'Fires, explosions, or uncontrolled hazardous material releases',
            ],
            [
                'id' => 'pasr-1',
                'category' => 'PASR',
                'question' => 'What is the main purpose of PASR?',
                'options' => [
                    'To reduce project overall cost',
                    'To ensure hazards and risks are addressed before activity commencement',
                    'To replace emergency safety drills during shutdown',
                    'To bypass safety critical device before activity commencement',
                ],
                'answerIndex' => 1,
                'correctAnswer' => 'To ensure hazards and risks are addressed before activity commencement',
            ],
            [
                'id' => 'pasr-2',
                'category' => 'PASR',
                'question' => 'Which online platform can PASR be submitted through?',
                'options' => ['myHSSE-UAUC', 'IPSS (Integrated Process Safety Solution)', 'ePTW', 'PRIME'],
                'answerIndex' => 1,
                'correctAnswer' => 'IPSS (Integrated Process Safety Solution)',
            ],
            [
                'id' => 'pasr-3',
                'category' => 'PASR',
                'question' => 'Which activities require PASR? i) Startup after TA/MSD. ii) Commissioning of new equipment. iii) SIPROD. iv) Platform abandonment.',
                'options' => ['i & ii', 'ii, iii & iv', 'None of the above', 'All of the above'],
                'answerIndex' => 3,
                'correctAnswer' => 'All of the above',
            ],
            [
                'id' => 'pasr-4',
                'category' => 'PASR',
                'question' => 'All of the items below are Cat A Action Items, EXCEPT:',
                'options' => ['Isolation of critical points', 'Verification on instrumentations', 'Closure of High Risk PHA Action Items', 'Housekeeping'],
                'answerIndex' => 3,
                'correctAnswer' => 'Housekeeping',
            ],
            [
                'id' => 'pasr-5',
                'category' => 'PASR',
                'question' => 'When do we need to raise a deviation?',
                'options' => [
                    'After startup activities are completed',
                    'When Cat A action items cannot be resolved before startup',
                    'When Cat B action items cannot be resolved before startup',
                    'When Cat A action items cannot be resolved after startup',
                ],
                'answerIndex' => 1,
                'correctAnswer' => 'When Cat A action items cannot be resolved before startup',
            ],
            [
                'id' => 'moc-1',
                'category' => 'MOC',
                'question' => 'MOC is important to ensure the proper level of review is applied to prevent adverse HSE effects from change.',
                'options' => ['TRUE', 'FALSE'],
                'answerIndex' => 0,
                'correctAnswer' => 'TRUE',
            ],
            [
                'id' => 'moc-2',
                'category' => 'MOC',
                'question' => 'The following are engineering changes that require MOC, EXCEPT:',
                'options' => [
                    'Changes to the operating characteristics of equipment, such as pump impellers or control valve trim',
                    'Use of non-standard parts as replacement',
                    'Changes in procedures that could lead to adverse HSE effects',
                    'Changing alarm or trip setting',
                    'Temporary repair and non-standard repair, such as pipe wrapping or pipe clamping',
                ],
                'answerIndex' => 2,
                'correctAnswer' => 'Changes in procedures that could lead to adverse HSE effects',
            ],
            [
                'id' => 'moc-3',
                'category' => 'MOC',
                'question' => 'For a temporary MOC with a duration of less than six months, who is the approver for the 1st extension?',
                'options' => ['Head of Production / Head of Integrated Facilities', 'Offshore Installation Manager / Terminal Manager or equivalent', 'Head of Asset'],
                'answerIndex' => 0,
                'correctAnswer' => 'Head of Production / Head of Integrated Facilities',
            ],
            [
                'id' => 'moc-4',
                'category' => 'MOC',
                'question' => 'For permanent MOC, the Offshore Installation Manager / Terminal Manager has the LOA to approve high-risk MOC.',
                'options' => ['TRUE', 'FALSE'],
                'answerIndex' => 1,
                'correctAnswer' => 'FALSE',
            ],
            [
                'id' => 'moc-5',
                'category' => 'MOC',
                'question' => 'A temporary change is intended to remain in place for a specified period only, and at the end of that period the change will be normalized and/or a permanent change implemented.',
                'options' => ['TRUE', 'FALSE'],
                'answerIndex' => 0,
                'correctAnswer' => 'TRUE',
            ],
            [
                'id' => 'bscpd-1',
                'category' => 'BSCPD',
                'question' => 'Maintenance isolates an impulse line upstream of a pressure transmitter to prevent further trips. They argue, "The SCPD itself is still healthy; only the impulse line is isolated." What should the panelman decide?',
                'options' => ['Allow since SCPD hardware is not removed', 'Allow with PTW only', 'Treat as SCPD bypass and require an approved SCPD certificate'],
                'answerIndex' => 2,
                'correctAnswer' => 'Treat as SCPD bypass and require an approved SCPD certificate',
            ],
            [
                'id' => 'bscpd-2',
                'category' => 'BSCPD',
                'question' => 'Which SCPD shall never be bypassed at any time?',
                'options' => ['Low-risk SCPD', 'Medium-risk SCPD', 'SCPD during shutdown', 'Very high-risk SCPD'],
                'answerIndex' => 3,
                'correctAnswer' => 'Very high-risk SCPD',
            ],
            [
                'id' => 'bscpd-3',
                'category' => 'BSCPD',
                'question' => 'What is the maximum allowable duration for an SCPD bypass before MOC is required?',
                'options' => ['4 hours', '30 days', '8 weeks', '12 weeks'],
                'answerIndex' => 3,
                'correctAnswer' => '12 weeks',
            ],
            [
                'id' => 'bscpd-4',
                'category' => 'BSCPD',
                'question' => 'An SCPD bypass was approved at 1700 hrs. During midnight shift handover, the incoming panelman says, "It is already approved, no need to discuss in detail." What is the correct action?',
                'options' => ['Accept since the certificate is valid', 'Re-brief full bypass status and record it in the shift handover note', 'Let the supervisor handle it next morning'],
                'answerIndex' => 1,
                'correctAnswer' => 'Re-brief full bypass status and record it in the shift handover note',
            ],
            [
                'id' => 'bscpd-5',
                'category' => 'BSCPD',
                'question' => 'A gas detector is removed for blasting activity. What must be ensured?',
                'options' => ['SCPD certificate only', 'PTW required for physical work and SCPD certificate', 'Verbal confirmation is enough'],
                'answerIndex' => 1,
                'correctAnswer' => 'PTW required for physical work and SCPD certificate',
            ],
            [
                'id' => 'sce-1',
                'category' => 'SCE',
                'question' => 'What is the primary purpose of Safety Critical Elements (SCE)?',
                'options' => ['To maximize production efficiency', 'To reduce maintenance costs', 'To prevent, control, or mitigate major accident hazards', 'To improve operator convenience'],
                'answerIndex' => 2,
                'correctAnswer' => 'To prevent, control, or mitigate major accident hazards',
            ],
            [
                'id' => 'sce-2',
                'category' => 'SCE',
                'question' => 'Which of the following best defines a Major Accident Hazard (MAH)?',
                'options' => [
                    'Any occupational injury resulting in lost time',
                    'An event with the potential to cause fatalities, severe environmental damage, or asset loss',
                    'Any unplanned equipment failure',
                    'A minor hydrocarbon leak',
                    'All of the above',
                ],
                'answerIndex' => 1,
                'correctAnswer' => 'An event with the potential to cause fatalities, severe environmental damage, or asset loss',
            ],
            [
                'id' => 'sce-3',
                'category' => 'SCE',
                'question' => 'What are the criteria for SCE group identification?',
                'options' => [
                    'Fixed hardware installed physically at facilities and identified as hardware barrier in safety studies',
                    'Barrier that is effective, independent and auditable to prevent/mitigate MAH',
                    'Equipment that is prone to immediate failure upon demand and can result in MAH',
                    'None of the above',
                    'All of the above',
                ],
                'answerIndex' => 4,
                'correctAnswer' => 'All of the above',
            ],
            [
                'id' => 'sce-4',
                'category' => 'SCE',
                'question' => 'Performance Standards for SCE typically define which key attributes?',
                'options' => ['Cost, delivery schedule, and vendor', 'Availability, functionality, reliability, and survivability', 'Operator training levels', 'Maintenance manpower requirements', 'All of the above'],
                'answerIndex' => 1,
                'correctAnswer' => 'Availability, functionality, reliability, and survivability',
            ],
            [
                'id' => 'sce-5',
                'category' => 'SCE',
                'question' => 'Which of the following is NOT a typical MAH for an offshore platform? i) Oil at low pressure. ii) Boat collision hazard to offshore structure. iii) Air under high pressure. iv) Transfer from boat to offshore platform.',
                'options' => ['ii, iii & iv', 'i, iii & iv', 'i & ii', 'All of the above'],
                'answerIndex' => 1,
                'correctAnswer' => 'i, iii & iv',
            ],
            [
                'id' => 'sce-6',
                'category' => 'SCE',
                'question' => 'Who is the approving authority (AA) for Operation SSPS during Operation phase?',
                'options' => ['Asset barrier owner', 'Discipline asset TA of discipline manager for IA', 'Project process safety TA', 'Asset process safety manager or equivalent for IA'],
                'answerIndex' => 3,
                'correctAnswer' => 'Asset process safety manager or equivalent for IA',
            ],
            [
                'id' => 'sol-1',
                'category' => 'SOL',
                'question' => 'What is the purpose of the alarm prioritization matrix?',
                'options' => ['To log all alarms for historical tracking purposes', 'To schedule maintenance tasks related to alarms', 'To help the operator identify and prioritize important alarms when multiple occur together'],
                'answerIndex' => 2,
                'correctAnswer' => 'To help the operator identify and prioritize important alarms when multiple occur together',
            ],
            [
                'id' => 'sol-2',
                'category' => 'SOL',
                'question' => 'Why do we need alarm shelving?',
                'options' => ['To permanently disable nuisance alarms', 'To reduce the number of alarms permanently shown on the panel', 'To allow the panel operator to temporarily inhibit alarms'],
                'answerIndex' => 2,
                'correctAnswer' => 'To allow the panel operator to temporarily inhibit alarms',
            ],
            [
                'id' => 'sol-3',
                'category' => 'SOL',
                'question' => 'When should an alarm be triggered for a spare pump that is not running?',
                'options' => ['Always, whenever the pump is off', 'Only when the pump is off but is supposed to be running', 'Never, regardless of its status'],
                'answerIndex' => 1,
                'correctAnswer' => 'Only when the pump is off but is supposed to be running',
            ],
            [
                'id' => 'sol-4',
                'category' => 'SOL',
                'question' => 'Why does alarm flooding occur?',
                'options' => ['Regular staff meetings', 'Shutdowns', 'Routine inspections'],
                'answerIndex' => 1,
                'correctAnswer' => 'Shutdowns',
            ],
            [
                'id' => 'sol-5',
                'category' => 'SOL',
                'question' => 'True or false: Safe Operating Limit (SOL) is a functional value and is typically a process parameter such as temperature, pressure or flow. Exceeding these limits would typically result in reduced product quality or process upset, not catastrophic failure. SOLs are provided in operating procedures with further instruction on the consequence of exceeding the limits and the steps to correct the exceeded limits.',
                'options' => ['TRUE', 'FALSE'],
                'answerIndex' => 0,
                'correctAnswer' => 'TRUE',
            ],
            [
                'id' => 'sol-6',
                'category' => 'SOL',
                'question' => 'True or false: COP is a process parameter that at some measurable level indicates an approach to a major hazard event, such as the potential release of toxic or hazardous substance, fire, explosion, sudden energy release, or other process-related incident that could result in life-threatening injury, fatality, environmental damage, or asset damage.',
                'options' => ['TRUE', 'FALSE'],
                'answerIndex' => 0,
                'correctAnswer' => 'TRUE',
            ],
            [
                'id' => 'sol-7',
                'category' => 'SOL',
                'question' => 'True or false: Mechanical Design Limit is defined by codes, standards, or equipment vendors and is applied to piping and equipment. Examples include design pressure and design temperature, often expressed as Maximum Allowable Working Pressure (MAWP) at a specified temperature.',
                'options' => ['TRUE', 'FALSE'],
                'answerIndex' => 0,
                'correctAnswer' => 'TRUE',
            ],
            [
                'id' => 'sol-8',
                'category' => 'SOL',
                'question' => 'As per PCSB Management of Change (MOC) Procedure, MOC is required when changing the setpoint of alarms (high alarm or low alarm) that are not triggering shutdown or trips.',
                'options' => ['TRUE', 'FALSE'],
                'answerIndex' => 0,
                'correctAnswer' => 'TRUE',
            ],
            [
                'id' => 'sol-9',
                'category' => 'SOL',
                'question' => 'True or false: Discipline engineers identify relevant parameters and their SOL for equipment, ensure the SOL database is developed, reviewed, and updated throughout the life cycle, and ensure the approved SOL database is submitted to the PSI Coordinator for compilation as part of handover documents.',
                'options' => ['TRUE', 'FALSE'],
                'answerIndex' => 0,
                'correctAnswer' => 'TRUE',
            ],
            [
                'id' => 'prd-1',
                'category' => 'PRD',
                'question' => 'Which of the following is NOT a type of Pressure Relief Device (PRD)?',
                'options' => ['Pressure Safety Valve (PSV)', 'Rupture Disc', 'Blowdown Valve (BDV)', 'Rupture Pin'],
                'answerIndex' => 2,
                'correctAnswer' => 'Blowdown Valve (BDV)',
            ],
            [
                'id' => 'prd-2',
                'category' => 'PRD',
                'question' => 'Which of the following is the primary function of a Pressure Relief Device (PRD)?',
                'options' => ['To measure temperature', 'To release excess pressure', 'To control flow rate', 'To measure the pressure within the system'],
                'answerIndex' => 1,
                'correctAnswer' => 'To release excess pressure',
            ],
            [
                'id' => 'prd-3',
                'category' => 'PRD',
                'question' => 'When does a pressure relief device activate?',
                'options' => ['When the temperature of the system increases', 'When the system pressure exceeds a predetermined limit', 'When the fluid level in the system is too low', 'When the flow rate drops below a certain level'],
                'answerIndex' => 1,
                'correctAnswer' => 'When the system pressure exceeds a predetermined limit',
            ],
            [
                'id' => 'prd-4',
                'category' => 'PRD',
                'question' => 'Which type of equipment commonly uses pressure relief devices?',
                'options' => ['Electric Motor', 'Compressor', 'Uninterruptible power supply', 'Flare Stack'],
                'answerIndex' => 1,
                'correctAnswer' => 'Compressor',
            ],
            [
                'id' => 'prd-5',
                'category' => 'PRD',
                'question' => 'A relief valve is opening and closing repeatedly. This is known as:',
                'options' => ['Pop action', 'Chattering', 'Reseating', 'Blowdown'],
                'answerIndex' => 1,
                'correctAnswer' => 'Chattering',
            ],
        ];
    }

    /** @return array<int, array{id: string, category: string, question: string, options: list<string>, answerIndex: int, correctAnswer: string}> */
    public static function getRandomQuestions(int $count = 10): array
    {
        $questions = static::getQuestions();
        shuffle($questions);

        return array_slice($questions, 0, min($count, count($questions)));
    }
}
